-- MySQL Script generated by MySQL Workbench
-- Sat Sep 16 09:25:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema travenas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travenas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travenas` DEFAULT CHARACTER SET utf8 ;
USE `travenas` ;

-- -----------------------------------------------------
-- Table `travenas`.`connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travenas`.`connections` ;

CREATE TABLE IF NOT EXISTS `travenas`.`connections` (
  `connectionid` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(255) NULL DEFAULT NULL,
  `fromDest` VARCHAR(255) NULL DEFAULT NULL,
  `toDest` VARCHAR(255) NULL DEFAULT NULL,
  `depart` VARCHAR(255) NULL DEFAULT NULL,
  `arrival` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`connectionid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `travenas`.`sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travenas`.`sections` ;

CREATE TABLE IF NOT EXISTS `travenas`.`sections` (
  `sectionid` INT(11) NOT NULL AUTO_INCREMENT,
  `connection` INT(11) NOT NULL,
  `fromStation` VARCHAR(255) NULL DEFAULT NULL,
  `toStation` VARCHAR(255) NULL DEFAULT NULL,
  `route` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`sectionid`),
  INDEX `connection` (`connection` ASC),
  CONSTRAINT `sections_ibfk_1`
    FOREIGN KEY (`connection`)
    REFERENCES `travenas`.`connections` (`connectionid`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
